version: "3.7"  # optional since v1.27.0
services:
  #reactApp
  reactfrontend:
   
    build:
      context: /Users/ellarnol/finalTikTokClone/finaltktk/frontend
      dockerfile: Dockerfile.client 
    ports:
      - "888:80"    #external:internal frontend 
    depends_on:
      - db
  node:
  
    build:
      context: .
      dockerfile: Dockerfile.dev_node
    ports: 
      - "9000:9000"    #external:internal frontend connects to node backed 
    depends_on:
      - db
    #avoid the the Error: connect ECONNREFUSED 127.0.0.1:27017 allows the 
    #nodeserver to wait until database:port are avail before attempting to connect
              
  db:
    volumes:
      - /Users/ellarnol/mongoScratchSpace:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"             

 # database connection url via mongoose "mongodb://db:27017/jl";


  # netstat -an -ptcp | grep LISTEN  check for listening ports 
  # docker rm $(docker ps -a -q) --force     - delete all containers - free up ports for dev environment